name: ModAct
version: '${project.version}'
main: com.github.metallnt.modact.ModAct
api-version: 1.19
description: 'Пример реализации конфига'
author: Metall
softdepend:
  - Vault
commands:
  modact:
    description: Главная команда плагина ModAct
    usage: /[modact,mac] help|reload|addexact|delexact|addmask|delmask|addblockdestroy|delblockdestroy|debug
    aliases:
      - mac
permissions:
  modact.help:
    default: op
    description: Справка по командам
  modact.reload:
    default: op
    description: Перезагрузка плагина
  modact.add:
    default: op
    description: Добавление блока в один из списков
  modact.delete:
    default: op
    description: Удаление блока из одного из списков
  modact.notification:
    default: true
    description: Отключение оповещений о правилах мира